# Use an official Node.js runtime as the base image
FROM node:14-alpine

RUN apk add curl

# Install selenium-side-runner globally
RUN npm install -g selenium-side-runner

# Set the working directory in the container
WORKDIR /app

COPY scripts/run_test.sh /app/run_test.sh
COPY sides/Test.side /app/Test.side



CMD ["sh", "run_test.sh"]
